#state can be either "awake" or "NREM"
#brain_state: "NREM"
brain_state: "awake"
use_nestml: False
use_single_compartment_environment: True
#exc_neu_params_filename: "Ca-AdEx_neural_params.yaml"
inh_neu_params_filename: "standard_AdEx_inh_neural_params.yaml"
exc_neu_params_filename: "standard_AdEx_exc_neural_params.yaml" 
#exc_neu_params_filename: "MC-g0_like-exc_neural_params.yaml"
cf: 1.0

network:
  num_exc_neu_per_pop: 20
  num_exc_pop: 4
  conn_rule: "pairwise_bernoulli"
  p_conn_exc: 1.0
  p_conn_inh: 1.0
  use_exc_recurrency: True
  use_poisson_generators: True
  inter_pop_conn: False
  num_poisson_generators: 20
  use_dc_exc_injectors: False
  use_dc_inh_injector: True

  default_plasticity:
    synapse_model: 'stdp_synapse'
    tau_plus: 20
    lambda: 0.1 
    alpha: 1.05 
    mu_plus: 1.0
    mu_minus: 1.0
    weight: 0.01
    Wmax: 'from-static_synaptic_default_value'
    delay: 'from-exc_to_exc_delay_ms'

contextual_poisson:
  awake:
    basic_rate: 3000.0
    poisson_weight: 0.6
    spreading_factor: 4.0
    events:
    - start_time_ms: 2000.0
      stop_time_ms: 3000.0
      target_population: 0
    - start_time_ms: 4000.0
      stop_time_ms: 5000.0
      target_population: 1
    - start_time_ms: 6000.0
      stop_time_ms: 7000.0
      target_population: 2
    - start_time_ms: 8000.0
      stop_time_ms: 9000.0
      target_population: 3
    - start_time_ms: 10000.0
      stop_time_ms: 11900.0
      target_population: 0
    - start_time_ms: 12000.0
      stop_time_ms: 13900.0
      target_population: 1
    - start_time_ms: 14000.0
      stop_time_ms: 15900.0
      target_population: 2
    - start_time_ms: 16000.0
      stop_time_ms: 17900.0
      target_population: 3  
    - start_time_ms: 30000.0
      stop_time_ms: 31500.0
      target_population: 0
    - start_time_ms: 32000.0
      stop_time_ms: 33500.0
      target_population: 1
    - start_time_ms: 34000.0
      stop_time_ms: 35500.0
      target_population: 2
    - start_time_ms: 36000.0
      stop_time_ms: 37500.0
      target_population: 3
  NREM:
    basic_rate: 0.0
    poisson_weight: 0.6
    spreading_factor: 4.0
    events:
    - start_time_ms: 44000.0
      stop_time_ms: 44000.0
      target_population: 0

poisson:
  awake:
    poisson_basic_rate: 600     #480.0
    poisson_delta: 0.0
    poisson_noise_spreading_factor: 4.0
    poisson_weight: 0.6
  NREM:
    poisson_basic_rate: 480.0
    poisson_delta: 0.0
    poisson_noise_spreading_factor: 4.0
    poisson_weight: 0.6

# inhibitory_poisson:
#   awake:
#     poisson_basic_rate: 600     #480.0
#     poisson_delta: 0.0
#     poisson_noise_spreading_factor: 4.0
#     poisson_weight: 0.6


weights:
  awake:
    recurrent_weight: 9.5 
    inh_to_exc_weight: -0.85
    exc_to_inh_weight: 7.0
    inh_to_inh_weight: -1.0 
    inter_pop_weight: 0.0           #0.01
  NREM:
    recurrent_weight: 19.0
    inh_to_exc_weight: -1.7
    exc_to_inh_weight: 7.0 
    inh_to_inh_weight: -1.0
    inter_pop_weight: 0.0           #0.02


dc_exc:
  amplitudes:
  - 0
  - 0
  delay: 1.0
  weight: 1.0
dc_inh:
  amplitude: 0.0
  delay: 1.0
  weight: 1.0
