brain_state: "awake"
use_nestml: True
inh_neu_params_filename: "standard_AdEx_inh_neural_params.yaml"
## uncomment for single compartment
use_single_compartment_environment: True
exc_neu_params_filename: "standard_AdEx_exc_neural_params.yaml" 
## uncomment for two-compartment
use_single_compartment_environment: False
exc_neu_params_filename: "Ca-AdEx_neural_params.yaml"

# conversion factor for synaptic conductances in multi comp network
cf: 1.15

weights:
  awake:
    recurrent_weight: 12.
    inh_to_exc_weight: -1.5
    exc_to_inh_weight: 7.0
    inh_to_inh_weight: -1.0 
    inter_pop_weight: 0.0   

contextual_poisson:
  awake:
    basic_rate: 3000.0
    poisson_weight:  4.0 
    spreading_factor: 4.0
    events:
    - start_time_ms: 5000.0
      stop_time_ms: 5025.0
      target_population: 0
    - start_time_ms: 5100.0
      stop_time_ms: 5125.0
      target_population: 1

contextual_inhibition:
  awake:
    basic_rate: 1000.0
    poisson_weight: 2.0
    spreading_factor: 4.0
    events:
    - start_time_ms: 4800
      stop_time_ms: 4990.0
      target_population: 0
    - start_time_ms: 4900
      stop_time_ms: 5090.0
      target_population: 1

poisson:
  awake:
    poisson_noise_spreading_factor: 4.0
    poisson_basic_rate: 600 
    poisson_delta: 0.0
    poisson_weight: 1.0